### ISSUE TITLE
Error:Execution failed for task ':app:processDebugManifest'.

### ISSUE THREAD

**Issue by ThiruSoft** [mypoolin/mypoolin-sdk#1]
Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed with multiple errors, see logs

G:\ERB Version5New\ERB Version5\erb\app\src\main\AndroidManifest.xml:62:9-41 Error:
	Attribute application@label value=(@string/app_name) from AndroidManifest.xml:62:9-41
	is also present at [com.mypoolin:sdk-pg-lite:0.0.1] AndroidManifest.xml:16:9-41 value=(@string/sdk_name).
	Suggestion: add 'tools:replace="android:label"' to <application> element at AndroidManifest.xml:58:5-251:19 to override.

G:\ERB Version5New\ERB Version5\erb\app\src\main\AndroidManifest.xml:65:9-47 Error:
	Attribute application@theme value=(@style/AppTheme_custom) from AndroidManifest.xml:65:9-47
	is also present at [com.mypoolin:sdk-pg-lite:0.0.1] AndroidManifest.xml:18:9-40 value=(@style/SDKTheme).
	Suggestion: add 'tools:replace="android:theme"' to <application> element at AndroidManifest.xml:58:5-251:19 to override.

**Comment by anaghvj** [comment]
Please add 
 'tools:replace="android:theme,android:label"
